**Import necessary libraries**

In [ ]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
%matplotlib inline

**Load the dataset**

In [ ]:
dataset=pd.read_csv('air_traffic_data.csv')
dataset.columns

Index(['Activity Period', 'Operating Airline', 'Operating Airline IATA Code',
       'Published Airline', 'Published Airline IATA Code', 'GEO Summary',
       'GEO Region', 'Activity Type Code', 'Price Category Code', 'Terminal',
       'Boarding Area', 'Passenger Count', 'Adjusted Activity Type Code',
       'Adjusted Passenger Count', 'Year', 'Month'],
      dtype='object')

**3. Exploratory Data Analysis and Data Preprocessing**

In [ ]:
# view the first five rows of the dataset.
dataset.head()

Activity Period Operating Airline  ...  Year Month
0           200507      ATA Airlines  ...  2005  July
1           200507      ATA Airlines  ...  2005  July
2           200507      ATA Airlines  ...  2005  July
3           200507       Air Canada   ...  2005  July
4           200507       Air Canada   ...  2005  July

[5 rows x 16 columns]

In [ ]:
dataset.drop(['Passenger Count'],axis=1,inplace=True)
dataset.drop(['Year','Month'],axis=1,inplace=True)
dataset.drop(['Operating Airline IATA Code','Published Airline IATA Code'],axis=1,inplace=True)

In [ ]:
dataset.drop(['Activity Type Code'],axis=1,inplace=True)

In [ ]:
# Storing independent variables in x and dependent variables in y.
x=dataset.iloc[:,:-1]
y=dataset.iloc[:,-1].values
x

Activity Period  ... Adjusted Activity Type Code
0               200507  ...                    Deplaned
1               200507  ...                    Enplaned
2               200507  ...          Thru / Transit * 2
3               200507  ...                    Deplaned
4               200507  ...                    Enplaned
...                ...  ...                         ...
15002           201603  ...                    Enplaned
15003           201603  ...                    Deplaned
15004           201603  ...                    Enplaned
15005           201603  ...                    Deplaned
15006           201603  ...                    Enplaned

[15007 rows x 9 columns]

In [ ]:
# split the data into training set and test set in 4:1 ratio.
from sklearn.model_selection import train_test_split
x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=0.2,random_state=1)

In [ ]:
# Converting categorical columns into numerical using label encoding
from sklearn.preprocessing import LabelEncoder
le_GS=LabelEncoder()
le_Price=LabelEncoder()
x_train['GEO Summary']=le_GS.fit_transform(x_train.iloc[:,3])
x_train['Price Category Code']=le_Price.fit_transform(x_train.iloc[:,5])
x_test['GEO Summary']=le_GS.fit_transform(x_test.iloc[:,3])
x_test['Price Category Code']=le_Price.fit_transform(x_test.iloc[:,5])

/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:5: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  """
/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:6: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  
/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:7: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-doc

In [ ]:
# One Hot Encoding
columns=['Operating Airline', 'Published Airline', 'GEO Region', 'Terminal','Boarding Area', 'Adjusted Activity Type Code']
from sklearn.preprocessing import OneHotEncoder
enc = OneHotEncoder(sparse=False)
enc.fit(x_train[columns])


OneHotEncoder(categories='auto', drop=None, dtype=<class 'numpy.float64'>,
              handle_unknown='error', sparse=False)

In [ ]:
a=enc.transform(x_train[columns])
a

array([[0., 0., 0., ..., 1., 0., 0.],
       [0., 0., 0., ..., 1., 0., 0.],
       [0., 0., 0., ..., 1., 0., 0.],
       ...,
       [0., 0., 0., ..., 0., 1., 0.],
       [1., 0., 0., ..., 0., 0., 1.],
       [0., 0., 0., ..., 0., 1., 0.]])

In [ ]:
x_train=x_train.values

In [ ]:
b=enc.transform(x_test[columns])
b

array([[0., 0., 0., ..., 1., 0., 0.],
       [0., 0., 0., ..., 1., 0., 0.],
       [0., 0., 0., ..., 0., 0., 1.],
       ...,
       [0., 0., 0., ..., 0., 0., 1.],
       [0., 0., 0., ..., 0., 1., 0.],
       [0., 0., 0., ..., 0., 1., 0.]])

In [ ]:
x_train=np.concatenate((x_train,a),1)

In [ ]:
pd.DataFrame(x_train).isnull().sum()

0      0
1      0
2      0
3      0
4      0
      ..
174    0
175    0
176    0
177    0
178    0
Length: 179, dtype: int64

In [ ]:
x_test=np.concatenate((x_test,b),1)

In [ ]:
x_test

array([[201311, 'Air France', 'Air France', ..., 1.0, 0.0, 0.0],
       [201312, 'Air New Zealand', 'Air New Zealand', ..., 1.0, 0.0, 0.0],
       [201206, 'United Airlines - Pre 07/01/2013',
        'United Airlines - Pre 07/01/2013', ..., 0.0, 0.0, 1.0],
       ...,
       [201101, 'United Airlines - Pre 07/01/2013',
        'United Airlines - Pre 07/01/2013', ..., 0.0, 0.0, 1.0],
       [200802, 'Hawaiian Airlines', 'Hawaiian Airlines', ..., 0.0, 1.0,
        0.0],
       [201004, 'United Airlines - Pre 07/01/2013',
        'United Airlines - Pre 07/01/2013', ..., 0.0, 1.0, 0.0]],
      dtype=object)

In [ ]:
x_train=pd.DataFrame(x_train)

In [ ]:
x_train

0                                 1    ... 177 178
0      201505                   United Airlines  ...   0   0
1      201510                  SkyWest Airlines  ...   0   0
2      201108                       Air Canada   ...   0   0
3      200706                         Air China  ...   1   0
4      201108                  SkyWest Airlines  ...   0   0
...       ...                               ...  ...  ..  ..
12000  200602  United Airlines - Pre 07/01/2013  ...   0   1
12001  200903         Lufthansa German Airlines  ...   1   0
12002  201404                   Alaska Airlines  ...   1   0
12003  200509                      ATA Airlines  ...   0   1
12004  201502                    Japan Airlines  ...   1   0

[12005 rows x 179 columns]

In [ ]:
x_train=x_train.drop(columns=[1,2,4,6,7,8],axis=1)
x_test=pd.DataFrame(x_test)
x_test=x_test.drop(columns=[1,2,4,6,7,8],axis=1)
x_test=x_test.values
x_train=x_train.values
from sklearn import tree
reg=tree.DecisionTreeRegressor()
reg=reg.fit(x_train,y_train)

In [ ]:
#y_pred=reg.predict(x_test)

In [ ]:
# RMSE
from sklearn.metrics import  mean_squared_error
DT=mean_squared_error(y_pred,y_test)

In [ ]:
DT

53595758.16955363

In [ ]:
from sklearn.metrics import r2_score
r2_score(y_test, y_pred) 

0.98682196328571

In [ ]:
x_train

array([[201505, 0, 1, ..., 1.0, 0.0, 0.0],
       [201510, 0, 1, ..., 1.0, 0.0, 0.0],
       [201108, 1, 1, ..., 1.0, 0.0, 0.0],
       ...,
       [201404, 0, 1, ..., 0.0, 1.0, 0.0],
       [200509, 0, 0, ..., 0.0, 0.0, 1.0],
       [201502, 1, 1, ..., 0.0, 1.0, 0.0]], dtype=object)

In [ ]:
from sklearn.ensemble import RandomForestRegressor
regressor=RandomForestRegressor(n_estimators=10,random_state=0)
regressor.fit(x_train,y_train)
y_pred1=regressor.predict(x_test)

In [ ]:
r2_score(y_pred1,y_test)

0.9870759946430739

In [ ]:
mean_squared_error(y_pred1,y_test)

52424940.00279481